AWSTemplateFormatVersion: 2010-09-09
Description: "S3 Template"

Parameters:
  #---------------------------------------------------------------------#
  # Common
  #---------------------------------------------------------------------#
  Prefix:
    Type: String
    Default: "stg"

  S3BucketName: 
    Type: String
    Default: "s3-log-674078804300"

Resources: 
  #---------------------------------------------------------------------#
  # S3 Bucket
  #---------------------------------------------------------------------#
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Sub ${Prefix}-${S3BucketName}
      PublicAccessBlockConfiguration:
           BlockPublicAcls: true
           BlockPublicPolicy: true
           IgnorePublicAcls: true
           RestrictPublicBuckets: true
      VersioningConfiguration: 
        Status: Suspended
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: 
             SSEAlgorithm: AES256
            BucketKeyEnabled: true
      Tags:
        - Key: Name
          Value: !Sub ${Prefix}-${S3BucketName}  

  #---------------------------------------------------------------------#
  # S3 VPCエンドポイント
  # PrivateDnsEnabledの記述不要
  # Gateway型の場合SubnetIdsの記述不要 -> エラーになる
  #---------------------------------------------------------------------#
  S3Endpoint: 
    Type: AWS::EC2::VPCEndpoint
    Properties:
        VpcEndpointType: Gateway
        ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
        RouteTableIds:
             - !ImportValue PrivateRouteTable
        VpcId: !ImportValue StgVPC-From-Ec2-Vpcendpoint

